mariadb:
    image: mariadb
    environment: 
        MYSQL_ROOT_PASSWORD: password 
myadmin:
    image: corbinu/docker-phpmyadmin
    links:
        - mariadb:mysql
    ports:
        - 8181:80
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: password

